baseURL = "https://memogarcia.mx"
languageCode = "en-us"
title = "Memo Garcia"
theme = "elephants"

[params]
    author = "Memo Garcia"
    github = "memogarcia"
    gitlab = "memogarcia"
    sitename = "Memo Garcia"